### PR TITLE
Output formatting changes in px_uploader.py

### PR DESCRIPTION
**Pull request by rydsfoz**
Some changes to the formatting of the output of the program px_uploader.py

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Need to check on the progress bar in the PX4 repo - did you bring that over from there?

**Comment by rydsfoz** [comment]
I did not remember to look at the version of the repository PX4/Firmware, but the version of the progress bar is a little different. There are other things added, for example, show a review of chips. I'll take a better look at the version of PX4/Firmware repository.

**Comment by davids5** [comment]
@rydsfoz 

Thank you!

It would be great if you would add these changes to the version on Firmware @ master and pull it in here.
 
Please let me know when this is ready.

David

**Comment by LorenzMeier** [comment]
Closing as stale.

**Pull request closed without merging**
