### PR TITLE
I2C interface for bootloader

### PR DESCRIPTION
**Pull request by muharred**
I've added F0 chip build to list of supported chips. Tested on STM32F030C8T6 via USART.
After that I've updated main bl.c with slave I2C interface option and added I2C interface to the F0 build I've used. Worked fine.  
The protocol is described in bl.c immediately after USART protocol description.

Known problems:  

- First of all, since I2C interface works on interrupts, during flash writes (especially erase) communication is not possible (at least on F0 chips flash reads are not possible during flash writes). I've used a work around for this - protocol has "get timeout" commands that return how long the updater needs to wait after erase/program before sending any new command. Potential better solution is marked as TODO above the I2C interrupt handling function - move the handler to RAM.
- Another problem is that F0 chips have a slightly different I2C register options (only F3 chips are almost the same, according to libopencm3 defines), so current version will only work for F0 chips. Probably, the best way would be to update libopencm3 with some kind of common API or define a set of functions to be implemented in chip-specific files. Anyway, it should be fairly easy to adapt existing handler to more general API calls, so it might be useful to have this implementation in master even though it only works for F0 chips. Unfortunately, I don't have any other chips at hand to improve the implementation and don't really have the time right now. If anyone is interested, the differences in I2C registers I've spotted in libopencm3 defines: other chips have only one data register instead of separate RX/TX data, names of available interrupts for I2C are different and "enable event interrupts" seems to be responsible for both RX and TX interrupts, there is no "clear interrupt" register, so reference manuals will need to be checked if conditions for clearing an interrupt are met by existing handler.

For initial build I've used F1 build as a basis and have separate commits for "copy from F1 build" and then modifications to it. So initial review should be easier on by-commit basis.  
If I2C implementation is not really needed, I can do another PR with just USART F0 implementation.

Another thing - I've uploaded the firmware manually, so I haven't added a jig configuration file for F0 chips.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! @davids5 Could you review?

**Comment by davids5** [comment]
@muharred - 

Thank you! This is very interesting. What is the use case? How is a host interfaced?

Would you be able to to embrace the "bootloader uses an interface" abstraction?

Creating a I2C interface set in a new set of file i2c.{h.c}
cinit(void);
cfini(void);
cin(void);
cout(uint8_t *buf, unsigned len);

Then looking at poling the the I2C the way the USB one is done.

The overall goal would be very little changes to the bl.c file. 

Would this be doable?

**Comment by muharred** [comment]
@davids5 

The use case is the following - we have a drone with Alex Moss' Simple BGC-driven Gimbal. We wanted to add automatic control of the mounted GoPro camera. Wiring an UART to the main board would be tricky, so we've had to use Simple BGC's I2C bus. So the end result is: main STM32 chip sends UART read/write packets to the Simple BGC (specifying the number of bytes to be read/written), which translates them to I2C packets and sends the result back to the main chip. For all commands main chip is the initiator as Simple BGC doesn't have an ability to detect an incoming I2C communication and automatically generate a packet to the main chip.

I'll look into the possibility to embrace the abstraction. My first impulse was to use it, but then at a quick glance I saw several problems with this approach and decided to use the current approach.  
I foresee that cout-s are going to be very tricky as we will either need to force the uploader to read each cout separately, or add an additional command "how many bytes do you have for me" so that the uploader can read the whole buffer and then parse it. Also, the bootloader interface will still need the "how long does the uploader needs to wait before trying to read a reply" commands (because interrupts are not processed correctly during flash erase/writes), which depends both on the chip and the bootloader code - this will create an additional responsibility for any modification of the bl.c main loop.

**Comment by davids5** [comment]
@muharred - Thank you for the explanation. It is starting to gel for me. So I am sure I understand, would be able to provide a block diagram with all the CPUs involved and the HW interfaces? Please also add the SW protocols on the diagram used on each of the interfaces. 

We can do this off line if need be. skype:david_s5

**Comment by muharred** [comment]
@davids5 - Sure. I'll try to do it on the weekend, probably.

**Comment by LorenzMeier** [comment]
I presume this is stale and can be closed? @dagar ?

**Pull request closed without merging**
