### PR TITLE
Fix mRo-X2.1 ethernal Bootloader

### PR DESCRIPTION
**Pull request by tops4u**
When TELEM-1 is connected to unpowered Equipment which is pulling the RX line to low, the Bootloader will hang when the FMU is only powered over USB. This refers to https://github.com/PX4/Bootloader/issues/93

This has been cross-tested to be the case on FMUv2 Units as well (Dropix V2, AUAV-X2). Below Implementation will fix this. I was not able to test if this change will really detect Serial Line Breaks.

Bootloader v4 is immune to the above Problem, but this is obsolete since 5. Dec 2015.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome, thanks! @ksschwabe Do you have the opportunity to test this?

**Comment by LorenzMeier** [comment]
@davids5 In reality that's not doable for us as a requirement.

**Comment by tops4u** [comment]
@davids5 the new Code does only check that the Break Signal will not last the whole observation Period (60 Tics - as it was before), while the previous Code just checked that the Line was Low for at least 18 Tics, but this is also the case if Serial Equipment will pull RX Low while unpowered. 

As Equipment like Telemetry Radios should not be powered by the Flight Controller this would be an Issue if we just want to configure the FMU or collect Logfiles.

**Comment by tops4u** [comment]
@davids5 without being able to test it, IMHO the Code assumes that there will be a rising flank for a LOW signal that lasted at least 18 Tics. The original Ver. 5 Code assumed no flanks just 18 Tics LOW had been enough to stay in Bootloader. If a Build/Platform shall not use the UART at all, it could be disabled in the _hwconfig.h_ file for the specified Platform. There has been some code (check: 1770cfd)that checks for a VBUS (USB Supply) Voltage but as much as I understood, did not take any action on the result to disregard the UART. 

As I have no possibility to check all Platforms nor all possible ways to install the Firmware I would refrain from performing this change request.

**Comment by LorenzMeier** [comment]
Closing this as stale.

**Pull request closed without merging**
