### PR TITLE
WIP: Wireless bootloading update

### PR DESCRIPTION
**Pull request by AndreasAntener**
Follow-up on #49 
I modified the uploader script for OTA updates via UDP. I verified that this basically works, I can flash an FMUv2 in roughly 90 seconds. It is still a bit flaky though, one would need to spend more time on the timeout handling and the protocol in general. Also it still suffers from the same issues that are described in the original PR (see below).

Needs: https://github.com/dogmaphobic/mavesp8266/pull/31
(to make the Wifi act as transparent bridge)

I find this approach interesting because it makes OTA updates possible in general if you have a transparent serial bridge, however I will not spend more time on it for the moment.

@ksschwabe feel free to start off here again if you like

> This is the initial work that I have done on the wireless bootloading logic.
> 
> Changes:
> 
>    BL revision increased to 6
>    PROG_MULTI protocol changed
>        Previously the protocol was PROG_MULTI/len:1/data:len/EOC, I have now changed it to PROG_MULTI//len:1/data:len/crc:4/EOC
>    I need to send the address as well to say at what starting address this packet should be. This is because the response packet may not be received, in which case the same previous data packet would be sent and I need a way to ensure that that is written to the correct section of memory.
>    Added a flush to the bootloader RX buffer, so that if there is an error, (incorrect address, bad CRC, bad command) then the RX buffer is cleared for the next message that is sent.
>    Added two new failure response commands (BAD_ADDRESS and BAD_CRC). Admittedly I don't really use BAD_CRC for anything, so I could possibly remove that and just send a PROTO_INVALID response back to the uploader - please give me your input.
> 
> I have put the px_uploader script with my changes into this PR for the moment so that you can pull and test without having to have another PR on PX4/Firmware. I will make a "sister" PR for the update of the uploader on PX4/Firmware when we are ready to merge this in.
> 
> Changes to px_uploader:
> 
>    The uploader will wait for a sync for a timeout period. If no response has been received, it will try to resend the PROG_MULTI data.
>        If a "failed" or "invalid" response is received, it will resend the message
>        The uploader will try to program the data for up to 5 seconds. If it has not received a "successful" response, it will then timeout.
> 
> Problems:
> 
>    The compilation is now 156 bytes too large for the standard PXIO bootloader. We will have to see what we can do to reduce the code or perhaps increase the allocated space for the PXIO bootloader.
>    Currently the response packets do not have a CRC. Therefore there is the possibility that a response packet gets mangled in the air and is received as a valid "successful" response, when it should have been an invalid response.
>    Currently only the programming of the flash message has a CRC. None of the other traffic has CRCs, so there is the potential for bad data to be received on both sides. Such as the the Serial number and chip description reporting back to the uploader. Thoughts?
> 
> I think the code definitely needs a bit more work, but I would like a bit of feedback from you guys to tell me what direction I should take this. Give it a try, first with the an FTDI cable and then perhaps with your wireless module. I have tested it with an FDTI cable simulating bit and byte drops and have also used a Laird RM024 wireless module.
> 
> What do you guys think?

### CODE REVIEW

**Comment by AndreasAntener** [comment]
Note: it's possible that this doesn't work yet when powered from the PSM

Command to run it:
```
./px_uploader.py --udp 192.168.4.1 firmware.px4
```

**Comment by LorenzMeier** [comment]
@AndreasAntener See the Travis CI fail.

**Comment by AndreasAntener** [comment]
See comments. This is far from ready.

**Comment by ksschwabe** [comment]
@AndreasAntener : I haven't had time to try it out yet, and I probably won't for the next two weeks, but from a cursory look over the files and changes it looks good.

@AndreasAntener, one request: please rename UdpReciever to UdpReceiver (i.e., swap the 'i' and the 'e').

I see that the error in the Travis CI fail, is that the pxio_bl has overflowed by 172 bytes. We might be able to get around this by adding stronger optimisations to the pxio bootloader compilation.

Also don't forget that if you change the BL for the pxio, then the Px4IO uploader script in the main Px4/Firmware repo will also need to be updated.

**Comment by LorenzMeier** [comment]
Closing as stale. This got added and robustified since.

**Pull request closed without merging**
