### PR TITLE
V5 TELEM2 bootloader rebased

### PR DESCRIPTION
**Pull request by mhkabir**
Rebased version of #110

### CODE REVIEW

**Comment by davids5** [comment]
@mhkabir - I am fine with the change from the F7 side.  Has this been tested with many systems?  The concern is using non-standard baud rates on the host and companion. Can we document what HW and OS's we know work at this rate?

```
```
```
50                                  Ok.
75                                  Ok.
110                                 Ok.
134                                 Ok.
150                                 Ok.
200                                 Ok.
300                                 Ok.
600                                 Ok.
1200                                Ok.
1800                                Ok.
2400                                Ok.
4800                                Ok.
9600                                Ok.
19200                               Ok.
38400                               Ok.
57600                               Ok.
115200                              Ok.
230400                              stty: /dev/ttyS0: unable to perform
460800                              stty: /dev/ttyS0: unable to perform
500000                              stty: /dev/ttyS0: unable to perform
576000                              stty: /dev/ttyS0: unable to perform
921600                              stty: /dev/ttyS0: unable to perform
1000000                             stty: /dev/ttyS0: unable to perform
1152000                             stty: /dev/ttyS0: unable to perform
1500000                             stty: /dev/ttyS0: unable to perform
2000000                             stty: /dev/ttyS0: unable to perform
2500000                             stty: /dev/ttyS0: unable to perform
3000000                             stty: /dev/ttyS0: unable to perform
3500000                             stty: /dev/ttyS0: unable to perform
4000000                             stty: /dev/ttyS0: unable to perform
```

**Comment by mhkabir** [comment]
We have extensively tested this (for several months now, including pushing remote firmware updates to actual deployed vehicles) on the "typical" companion computer setup: Linux (Ubuntu 16.04/18.04) with FTDI adapters. Most setups I've seen personally utilize FTDI USB-UART adapters (or USB-UART chips directly built in to their mainboards) to interface to the companion system, but this is obviously a very small sample. It should be noted that the other mildly popular SiLabs CP2102 USB-UART chip does *not* support the high baudrate.

I cannot confirm that all other companion hardware will support 2Mbit, but I do think it's safe to merge given the benefits:
1. How much faster it makes the firmware upload.
2. The Pixhawk side has worked flawlessly so far.

**Comment by davids5** [comment]
@mhkabir  Why not add support to set the baurd rate in the bootloader: https://github.com/PX4/Bootloader/blob/master/bl.c#L104 ?
That will make this really work for everyone. Add the detection script logic to the uploader and then set the baud rate to the max that will work, not the max that worked for you on your HW.

**Comment by mhkabir** [comment]
That sounds good to me - let me have a look.

**Comment by LorenzMeier** [comment]
I presume this is stale by now?

**Comment by julianoes** [comment]
Closing as stale. Please re-open when you come back to this @mhkabir.

**Pull request closed without merging**
